#!/usr/bin/env tcsh

if($1<10) then
    set numstr = '000'$1
else if($1<100) then
    set numstr = '00'$1
else if($1<1000) then
    set numstr = '0'$1
endif

set finStr = 'rsl.out.'$numstr
echo $finStr
if ( $2 == 'n' ) then
    emacs -nw $finStr 
else
    emacs  $finStr &
endif
