#!/bin/csh
/bin/rm -rf ACME ||echo '-->Failed to delete ACME directory' && exit -1


~/bin/gitcln

#git clone git@github.com:ACME-Climate/ACME.git ||echo '-->Failed to colne ACME repo ' && exit -1
#cd ACME
#git submodule update --init||echo '-->Failed to init submodule ' && exit -1
#/bin/rm -rf .git/hooks
#git clone git@github.com:ACME-Climate/ACME-Hooks.git .git/hooks
#git config commit.template ${PWD}/.git/hooks/commit.template

#git branch
